name: release

on:
  push:
    branches: [release]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
jobs:
  bina-for-curl-download:
    name: Make bina.json
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Genetate bina.json
        run: cd ./cli && make bina
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: yomo-artifact
          path: ./cli/bin/bina.json
  build-darwin-amd64:
    name: Build MacOS x86-64 binary
    runs-on: macos-latest
    env:
      GOVER: 1.19
    steps:
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run go mod tidy
        run: go mod tidy
      - name: build & archive binaries
        run: cd ./cli && GOARCH=amd64 GOOS=darwin go build -o bin/yomo -ldflags "-s -w test" ../cmd/yomo/main.go
      - name: yomo bin
        run: ./bin/yomo
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: yomo-artifact
          path: ./cli/bin/**/*.tar.gz
