name: release

on:
  push:
    branches: [release]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
jobs:
  bina-for-curl-download:
    name: Make bina.json
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Genetate bina.json
        run: cd ./cli && make bina
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: yomo-artifact
          path: ./cli/bin/bina.json
  build-darwin-amd64:
    name: Build MacOS x86-64 binary
    runs-on: macos-latest
    env:
      GOVER: 1.19
    steps:
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run go mod tidy
        run: go mod tidy
      - name: build & archive binaries
        run: cd ./cli && make archive-release-darwin-amd64
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: yomo-artifact
          path: ./cli/bin/**/*.tar.gz
  publish:
    name: Publish binaries
    needs: [bina-for-curl-download, build-darwin-amd64]
    env:
      ARTIFACT_DIR: ./release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@master
        with:
          name: yomo-artifact
          path: ${{ env.ARTIFACT_DIR }}
      - name: lists artifacts
        run: ls -l ${{ env.ARTIFACT_DIR }}
      - name: build version
        run: cd ./cli && make cli_version
      - name: Get version
        id: tag
        run: echo "name=version::$(cat ./cli/VERSION)" >> $GITHUB_OUTPUT
      - name: publish binaries to github
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ steps.tag.outputs.version }}
          files: ${{ env.ARTIFACT_DIR }}/*
